spring:
  datasource:
    url: jdbc:mysql://localhost:3306/career_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.domain
  configuration:
    map-underscore-to-camel-case: true